(function(){
var f=navigator.userAgent.toLowerCase();google.isOpera=f.indexOf("opera")!=-1;google.isIE=document.all&&f.indexOf("msie")!=-1&&!google.isOpera;google.isSafari=f.indexOf("safari")!=-1;google.time=function(){return(new Date).getTime()};google.log=function(a,c){(new Image).src="/gen_204?atyp=i&ct="+a+"&cad="+c+"&zx="+google.time()};google.xhr=function(){var a=null;if(window.XMLHttpRequest)try{a=new XMLHttpRequest}catch(c){}else if(window.ActiveXObject)for(var d=0,b;b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0",
"MSXML2.XMLHTTP","Microsoft.XMLHTTP"][d++];)try{a=new ActiveXObject(b);break}catch(c){}return a};function g(a,c,d){var b=document.defaultView&&document.defaultView.getComputedStyle(a,""),e=b&&b.getPropertyValue(c);return document.defaultView&&b&&typeof e=="string"&&(d?e:parseInt(e,10))}google.getHeight=function(a){return g(a,"height")||a.offsetHeight};google.getWidth=function(a){return g(a,"width")||a.offsetWidth};google.getColor=function(a){return a.currentStyle?a.currentStyle.color:g(a,"color",
1)};google.rhs=function(){};window.google.bind=function(a,c,d){var b="on"+c;if(a.addEventListener)a.addEventListener(c,d,false);else if(a.attachEvent)a.attachEvent(b,d);else{var e=a[b];a[b]=function(){var h=e.apply(this,arguments),i=d.apply(this,arguments);return h==undefined?i:(i==undefined?h:i&&h)}}};
})();
(function(){
window.google.stringify=function(a){var c,d,j,b="",f;switch(typeof a){case "object":if(a)if(a instanceof Array||typeof a.join=="function"&&typeof a.reverse=="function"){for(d=0;d<a.length;++d){f=window.google.stringify(a[d]);if(b)b+=",";b+=f}return"["+b+"]"}else if(typeof a.toString!="undefined"){for(d in a){f=a[d];if(typeof f!="undefined"&&typeof f!="function"){f=window.google.stringify(f);if(b)b+=",";b+=window.google.stringify(d)+":"+f}}return"{"+b+"}"}return"null";case "number":return isFinite(a)?
String(a):"null";case "string":j=a.length;b='"';for(d=0;d<j;d+=1){c=a.charAt(d);if(c>=" "){if(c=="\\"||c=='"')b+="\\";b+=c}else switch(c){case "\n":b+="\\n";break;case "\r":b+="\\r";break;case "\t":b+="\\t";break;default:c=c.charCodeAt();b+="\\u00"+Math.floor(c/16).toString(16)+(c%16).toString(16);break}}return b+'"';case "boolean":return String(a);default:return"null"}};google.History={};var e=[],g="#";google.History.client=function(a){e.push(a);return e.length-1};var h,i;function k(){var a=h.value;i=!(!a)?eval("("+a+")"):{}}google.History.save=function(a,c){if(h){k();if(!i[g])i[g]={};i[g][a]=c;h.value=google.stringify(i)}};function l(){i=null;h=document.getElementById("hcache");h&&window.setTimeout(function(){k();for(var a=0;a<e.length;++a)if(i&&i[g]&&i[g][a])e[a].call(null,i[g][a])},0)}l();google.rein.push(function(){g=google.pageState;l()});
})();
(function(){
var a,b;google.rhs=function(){if(!google.drhs)if(document.getElementById("mbEnd")&&(a||b)){var d=google.getHeight(document.getElementById("rhsline")),c=a?google.getHeight(a):0;if(b)c+=google.getHeight(b)+18;document.getElementById("rhspad").style.height=c>d?Math.min(9999,c-d)+"px":(google.isIE?"":0)}};function e(){a=document.getElementById("tads");b=document.getElementById("3po");google.rhs()}e();google.bind(window,"resize",google.rhs);google.rein.push(e);
})();
(function(){
var c=false,e=null,g,i,j,n="",q=e,r=e,s=e,u=-1,v,w,x,y,A,B,D,E=0,F=0,G=e,H=0;var I,J;
var aa="clients1.google.de";
function ca(a,b,d,m,l){v=a;w=b;J=document.getElementsByTagName("head")[0];D=["/complete/search","?hl=",google.kHL,(d?"&ds="+d:"")].join("");google.bind(v,"submit",da);w.setAttribute("autocomplete","off");google.bind(w,"blur",R);
w.onkeypress=S;google.bind(w,"keyup",T);i=j=g=w.value;x=document.createElement("table");
x.cellSpacing=x.cellPadding="0";y=x.style;x.className="gac_m";v.appendChild(x);R();U();google.bind(window,"resize",U);google.bind(window,"pageshow",function(f){if(f.persisted){A.value="f";B.value=w.value}});A=fa("aq","f");B=fa("oq",i);var k=document.createElement("style");document.getElementsByTagName("head")[0].appendChild(k);var h=e;h=k.sheet;
var p=function(f,o){var z=f+" { "+o+" }";h.insertRule(z,h.cssRules.length);};p(".gac_m","font-size:13px;cursor:default;line-height:17px;border:1px solid black;z-index:99;background:white;position:absolute;margin:0;");
p(".gac_b","background:#36c;color:white;");var C="white-space:nowrap;overflow:hidden;text-align:left;padding-left:3px;";p(".gac_c",C);p(".gac_d","white-space:nowrap;overflow:hidden;text-align:right;font-size:10px;color:green;padding:0 3px");p(".gac_b td","color:white");p(".gac_e","padding:0 3px 2px;font-size:10px;line-height:15px;text-align:right;color:#00c;text-decoration:underline");
W();(new Image).src="http://"+aa+"/generate_204";}
function U(){if(x){y.left=ga(w,"offsetLeft")+"px";y.top=ga(w,"offsetTop")+w.offsetHeight-1+"px";y.width=w.offsetWidth+"px";}}function fa(a,b){var d=document.createElement("input");d.type="hidden";d.name=a;d.value=b;return v.appendChild(d)}
function S(a){var b=a.keyCode;if(b==27&&ha()){R();X(i);a.cancelBubble=true;return a.returnValue=c}if(b==38||b==40){F++;F%3==1&&V(b);return c}}function T(a){var b=a.keyCode;if(F==0)V(b);F=0;}
function V(a){if(w.value!=g){i=w.value;B.value=i}a==40&&ia(u+1);a==38&&ia(u-1);U();if(n!=i&&!G)G=window.setTimeout(R,500);g=w.value;g==""&&!q&&W()}function ja(){if(H)return;if(s)s.className="gac_a";this.className="gac_b";s=this;for(var a=0,b;b=r[a];a++)b==s&&(u=a)}
function ia(a){if(!n&&i){j="";W();return}if(i!=n||!q)return;if(!r||r.length<=0)return;if(!ha()){Y();return}var b=r.length-1;if(s)s.className="gac_a";if(a==b||a==-1){u=-1;X(i);w.focus();A.value="f";return}else if(a>b)a=0;else if(a<-1)a=b-1;u=a;s=r.item(a);s.className="gac_b";X(s.completeString);A.value=s.completeId}
function R(){if(G){window.clearTimeout(G);G=e}y.visibility="hidden";}function Y(){y.visibility="visible";U();H=1}function ha(){return y.visibility=="visible"}
function ka(a){E>0&&E--;if(a[0]!=i)return;if(G){window.clearTimeout(G);G=e}n=a[0];x.innerHTML="";var d=c;for(var m=0,l;m<a[1].length;m++)if(l=a[1][m]){
d=true;var k=x.insertRow(-1);k.onclick=function(){X(this.completeString);da();v.submit();};
k.onmousedown=Z;k.onmouseover=ja;k.onmousemove=function(){if(H){H=0;ja.call(this)}};k.completeString=l[0];k.completeId=l[2];k.className="gac_a";var h=document.createElement("td");$(h,l[0]);h.className="gac_c";k.appendChild(h);var t=document.createElement("td");$(t,l[1]);t.className="gac_d";k.appendChild(t);}if(d){var o=x.insertRow(-1);o.onmousedown=Z;var f=document.createElement("td");f.colSpan=2;o.className="gac_e";o.appendChild(f);var z=document.createElement("span");z.style.cursor="pointer";f.appendChild(z);$(z,"Schließen");
z.onclick=function(){R();n="";window.clearTimeout(q);q=e;A.value="x"}}u=-1;r=x.rows;(r.length>0?Y:R)()}function da(){R();if(B.value!=w.value)A.value=r.item(u).completeId;else{B.value="";if(E>=10)A.value="o"}}
function W(){if(j!=i&&i){E++;I&&J.removeChild(I);I=document.createElement("script");I.src=["http://",aa,D,"&q=",encodeURIComponent(i)].join("");J.appendChild(I);w.focus()}j=i;var a=100;for(var b=1;b<=(E-2)/2;++b)a*=
2;a+=50;q=window.setTimeout(W,a)}function X(a){w.value=a;g=a}function ga(a,b){var d=0;while(a){d+=a[b];a=a.offsetParent}return d}function $(a,b){a.appendChild(document.createTextNode(b))}
function Z(a){a.stopPropagation();return c}window.google.ac={i:ca,h:ka};
})();
(function(){
window.ManyBox={};var e,g,h=1,j=google.History.client(i);function k(a){for(var b in e)if(e[b].c&&a(e[b]))return}function l(a,b,c,d,f){this.c=a;this.i=b;this.B=d;this.o=f;this.q="/mbd?"+(b?"docid="+b:"")+"&resnum="+a.replace(/[^0-9]/,"")+"&mbtype="+d+"&usg="+c+"&hl="+(google.kHL||"");this.e={};this.l="";g[a]={r:0,D:this.e,i:this.i,h:0};this.n=0}l.prototype.append=function(a){this.l+="&"+a.join("&")};function m(a,b){return document.getElementById("mb"+b+a.c)}function n(a,b){a.g.style.paddingTop=b+"px";
a.g.style.display=a.g.innerHTML?"":"none";if(b>a.n)a.n=b}function o(a){if(!a.A){a.A=1;a.d=m(a,"b");a.j=0;a.a=m(a,"l");a.m=a.a.getElementsByTagName("DIV")[0];a.p=a.a.getElementsByTagName("A")[0];a.z=a.p.innerHTML;a.o=a.o||a.z;a.m.title="Klicken Sie hier, um weitere Informationen zu erhalten.";a.a.F=function(b,c){var d=r(a.a),f=s(a.a);return b>d-5&&b<d+google.getWidth(a.a)+5&&c>f-5&&c<f+google.getHeight(a.a)+5};a.g=m(a,"f");n(a,0);a.a.onmousedown=t(a);a.a.onclick=u(a);a.a.go=function(){a.a.onmousedown();a.a.onclick()}}}function t(a){return function(){if(g[a.c].h){if(a.I++<3)google.log("manybox",[a.j?"close":"open","&id=",a.c,"&docid=",a.i,"&mbtype=",a.B,a.l].join(""))}else{var b=google.xhr();if(b){b.open("GET",a.q+a.l+"&zx="+google.time());a.t=0;b.onreadystatechange=function(){if(b.readyState==4){var c=0;if(b.status==200)try{eval(b.responseText);c=1}catch(d){}if(!c&&!a.C){g[a.c].h=0;a.C=1;a.q+="&cad=retry";a.a.onmousedown()}else{a.u&&v(a);a.t=0}}};a.t=1;b.send(null)}g[a.c].h=(a.I=1)}}}function u(a){return function(){g[a.c].h||
a.a.onmousedown();(a.u=a.t)||v(a)}}function z(a){if(!a.e.k){a.e.k="\x3cfont color\x3dred\x3eFehler:\x3c/font\x3e Der Server konnte Ihre Anforderung nicht ausführen. Versuchen Sie es in 30 Sekunden noch einmal.";a.G=a.a.onclick;a.a.onclick=function(){h=0;v(a);h=1;a.b.parentNode.removeChild(a.b);g[a.c].h=(a.e.k=(a.v=0));a.a.onclick=a.G}}if(!a.v){a.v=1;var b=document.getElementById("res");a.H=b&&r(a.d)>r(b)+google.getWidth(b);a.b=document.createElement("div");n(a,0);a.b.style.position="absolute";a.b.style.paddingTop=(a.b.style.paddingBottom="6px");a.b.style.display="none";a.b.className="med";var c=document.createElement("div");
a.b.appendChild(c);c.className="std";c.innerHTML=a.e.k;a.g.parentNode.insertBefore(a.b,a.g)}}function i(a){h=0;ManyBox.init();k(function(b){if(b.i==a[b.c].i){b.e=a[b.c].D;if(a[b.c].r!=b.j)v(b)}else a[b.c].h=0});g=a;h=1;google.History.save(j,g)}ManyBox.create=function(a,b,c,d,f){return new l(a,b,c,d,f)};ManyBox.register=function(a,b,c,d,f){return e[a]=ManyBox.create(a,b,c,d,f)};google.bind(document,
"click",function(a){a=a||window.event;var b=a.target||a.srcElement;while(b.parentNode){if(b.tagName=="A"||b.onclick)return;b=b.parentNode}k(function(c){if(c.a.F(a.clientX,a.clientY)){c.a.go();return 1}})});function A(){e={};g={};history.navigationMode=history.navigationMode&&"fast"}A();ManyBox.init=function(){k(o)};function B(a,b){a.b.style.clip="rect(0px,"+(a.d.width||"34em")+","+(b||1)+"px,0px)"}l.prototype.insert=function(a){this.e.k=a;google.History.save(j,g)};function s(a){return a.offsetTop+
(a.offsetParent?s(a.offsetParent):0)}function C(a){return a.offsetLeft+(a.offsetParent?C(a.offsetParent):0)}function r(a){return C(a)}function D(a){a.f=m(a,"cb");var b=a.f&&a.f.getAttribute("mbopen");if(b){eval(b);a.onopen(a.f)}}function E(a){a.b.style.display="none";a.m.style.backgroundPosition="-91px -74px";a.p.innerHTML=a.z;a.j=(g[a.c].r=0);google.History.save(j,g)}function F(a,b,c,d,f){var w=c>0?150:75,x=google.time()-f,y=x<w&&h?x/
w*c:(d>1?c-10:c),p=Math.max(a.s,b+y),q=p-a.s;B(a,q);a.d.style.height=p<0?0:(q?p+"px":"");n(a,Math.max(0,q-5));google.rhs();if(Math.abs(y)<Math.abs(c))window.setTimeout(function(){F(a,b,c,d-1,f)},30);else window.setTimeout(function(){c<0?E(a):D(a);if(!google.isIE&&a.H)a.b.style.width="100px";a.b.style.position=(a.d.style.height="");n(a,0);google.rhs();a.d.w=0},0)}function v(a){a.u=0;if(!a.d.w){a.d.w=1;var b;if(!a.j){a.s=google.getHeight(a.d);z(a);n(a,0);a.n=0;k(function(d){d.m.title=""});a.m.style.backgroundPosition=
"-105px -74px";a.p.innerHTML=a.o;B(a,1);a.b.style.position="absolute";a.b.style.display="";a.j=(g[a.c].r=1);google.History.save(j,g);b=a.b.offsetHeight}else{var c=a.f&&a.f.getAttribute("mbclose");if(c){eval(c);a.onclose(a.f)}b=a.s-google.getHeight(a.d);a.g.style.display="none";n(a,a.n);a.b.style.position="absolute"}F(a,google.getHeight(a.d),b,google.isSafari?2:1,google.time())}}google.dstr&&google.dstr.push(A);
})();
if(!window.gbar||!gbar.close){window.gbar={};(function(){var b=window.gbar,f,h;b.qs=function(a){var c=window.encodeURIComponent&&(document.forms[0].q||"").value;if(c)a.href=a.href.replace(/([?&])q=[^&]*|$/,function(i,g){return(g||"&")+"q="+encodeURIComponent(c)})};function j(a,c){a.visibility=h?"hidden":"visible";a.left=c+"px"}b.tg=function(a){a=a||window.event;var c=0,i,g=window.navExtra,d=document.getElementById("gbi"),e=a.target||a.srcElement;a.cancelBubble=true;if(!f){f=document.createElement(Array.every||window.createPopup?"iframe":"div");f.frameBorder="0";f.src="#";d.parentNode.appendChild(f).id="gbs";if(g)for(i in g)d.insertBefore(g[i],d.firstChild).className="gb2";document.onclick=b.close}if(e.className!="gb3")e=e.parentNode;do c+=e.offsetLeft;while(e=e.offsetParent);j(d.style,c);f.style.width=d.offsetWidth+"px";f.style.height=d.offsetHeight+"px";j(f.style,c);h=!h};b.close=function(a){h&&b.tg(a)}})();;};
(function (){
var a="google";if(window[a]){window[a].a={};window[a].b=1;window[a].report=function(h,g,i){var d="";{if(window[a].pt){d+="&srt="+window[a].pt;delete window[a].pt}try{d+="&tran="+window.external.tran}catch(n){}}{var j=document.getElementById("csi");if(j.value)return;j.value=1}var b=h.t,e=b.start;delete b.start;var k=[];for(var f in b)e&&k.push(f+"."+(b[f]>e?b[f]-e:e-b[f]));if(g)for(var l in g)d+="&"+l+"="+g[l];var c=new Image,m=window[a].b++;window[a].a[m]=c;c.onload=(c.onerror=function(){delete window[a].a[m]});
c.src=[i?i:"/csi","?v=3","&s="+(window[a].sn?window[a].sn:"GWS")+"&action=",h.name,d,"&rt=",k.join(",")].join("");c=null}};window.setTimeout(function(){if(google.timers&&google.timers.load.t){google.timers.load.t.xjs=(new Date).getTime();google.timers.load.t.ol&&google.report(google.timers.load,google.kCSI)}},0);
})();
if(google.y.first){for(var a=0,b;b=google.y.first[a];++a)b();delete google.y.first}for(a in google.y)google.y[a][1]?google.y[a][1].apply(google.y[a][0]):google.y[a][0].go();google.y.x=google.x;google.x=function(d,c){c&&c.apply(d);return false};google.y.first=[];
